export const FETCH_REVIEWS = 'FETCH_REVIEWS';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_REVIEWS_FAILURE = 'FETCH_REVIEWS_FAILURE';
export const SET_PLATFORM_FILTER = 'SET_PLATFORM_FILTER';
export const SET_RATING_FILTER = 'SET_RATING_FILTER';
export const SET_SORT_CONFIG = 'SET_SORT_CONFIG'; 